-- MySQL Script generated by MySQL Workbench
-- Thu Aug  9 20:58:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PurchaseOrder_Approval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseOrder_Approval` (
  `requestor_Id` INT NOT NULL,
  `po_number` VARCHAR(50) NULL,
  `Suuplier_ID` VARCHAR(45) NULL,
  `Supplier_Name` VARCHAR(100) NULL,
  `First_Name` VARCHAR(50) NULL,
  `Last_Name` VARCHAR(50) NULL,
  `Item` VARCHAR(200) NULL,
  `Item_Desc` VARCHAR(200) NULL,
  `unit_of_measure` VARCHAR(50) NULL,
  `quantity` INT NULL,
  `cost_per_item` DOUBLE NULL,
  `total_cost` DOUBLE NULL,
  `Reject` VARCHAR(45) NULL,
  `Approve` VARCHAR(45) NULL,
  `PO_Manager_Approval1` VARCHAR(100) NULL,
  `PO_Manager_Approval2` VARCHAR(100) NULL,
  `PO_Manager_Approval3` VARCHAR(100) NULL,
  PRIMARY KEY (`requestor_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registration` (
  `Rgistration_Id` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NULL,
  `Cost_Center` VARCHAR(100) NULL,
  `Department` VARCHAR(100) NULL,
  `Area` VARCHAR(100) NULL,
  `Account_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Rgistration_Id`),
  CONSTRAINT `fk_Registration_PurchaseOrder_Approval1`
    FOREIGN KEY (`Rgistration_Id`)
    REFERENCES `mydb`.`PurchaseOrder_Approval` (`requestor_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_Takeout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_Takeout` (
  `Registration_id` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Department` VARCHAR(45) NULL,
  `Cost_Center` INT NOT NULL,
  `Job_Order` INT NOT NULL,
  `Item_Id` INT NOT NULL,
  `Item_Desc` VARCHAR(100) NULL,
  `Quantity` INT NULL,
  `unit_of_measure` VARCHAR(45) NULL,
  `Item_expiration_date` DATETIME NULL,
  `Request_Total` DOUBLE NULL,
  `Requestor_email` VARCHAR(100) NULL,
  `Monthly_Budget` DOUBLE NULL,
  `Monthly_to_Date` DATETIME NULL,
  `Approve_Inventory_Takeout` VARCHAR(50) NULL,
  `Reject_Inventory_Takeout` VARCHAR(50) NULL,
  PRIMARY KEY (`Registration_id`, `Cost_Center`, `Job_Order`, `Item_Id`),
  CONSTRAINT `fk_Inventory_Takeout_Registration1`
    FOREIGN KEY (`Registration_id`)
    REFERENCES `mydb`.`Registration` (`Rgistration_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Structure` (
  `Cost_Center` INT NOT NULL,
  `Area` VARCHAR(100) NOT NULL,
  `Department` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Cost_Center`, `Area`, `Department`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cost_Center_Budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cost_Center_Budget` (
  `Annual_Budget` DOUBLE NULL,
  `Monthly_Budget` DOUBLE NULL,
  `Quaterly_Budget` DOUBLE NULL,
  `Monthly_To_Date` DOUBLE NULL,
  `Quaterly_To_Date` DOUBLE NULL,
  `Year_To_Date` DOUBLE NULL,
  `Cost_Center` INT NOT NULL,
  `Area` VARCHAR(100) NOT NULL,
  `Department` VARCHAR(100) NOT NULL,
  INDEX `fk_Cost_Center_Budget_Structure_idx` (`Cost_Center` ASC, `Area` ASC, `Department` ASC),
  CONSTRAINT `fk_Cost_Center_Budget_Structure`
    FOREIGN KEY (`Cost_Center` , `Area` , `Department`)
    REFERENCES `mydb`.`Structure` (`Cost_Center` , `Area` , `Department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cost_Center_Budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cost_Center_Budget` (
  `Annual_Budget` DOUBLE NULL,
  `Monthly_Budget` DOUBLE NULL,
  `Quaterly_Budget` DOUBLE NULL,
  `Monthly_To_Date` DOUBLE NULL,
  `Quaterly_To_Date` DOUBLE NULL,
  `Year_To_Date` DOUBLE NULL,
  `Cost_Center` INT NOT NULL,
  `Area` VARCHAR(100) NOT NULL,
  `Department` VARCHAR(100) NOT NULL,
  INDEX `fk_Cost_Center_Budget_Structure_idx` (`Cost_Center` ASC, `Area` ASC, `Department` ASC),
  CONSTRAINT `fk_Cost_Center_Budget_Structure`
    FOREIGN KEY (`Cost_Center` , `Area` , `Department`)
    REFERENCES `mydb`.`Structure` (`Cost_Center` , `Area` , `Department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PurchaseOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseOrders` (
  `requestor_Id` INT NOT NULL,
  `po_number` VARCHAR(45) NULL,
  `supplier_ID` VARCHAR(45) NULL,
  `Supplier_Name` VARCHAR(100) NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Item` VARCHAR(200) NULL,
  `Item_Desc` VARCHAR(200) NULL,
  `unit_of_measure` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `cost_per_item` DOUBLE NULL,
  `total_cost` DOUBLE NULL,
  PRIMARY KEY (`requestor_Id`),
  CONSTRAINT `fk_PurchaseOrders_Registration1`
    FOREIGN KEY (`requestor_Id`)
    REFERENCES `mydb`.`Registration` (`Rgistration_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_Reordering_Alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_Reordering_Alerts` (
  `Expiration_Date` DATETIME NULL,
  `Supplier_Id` INT NULL,
  `Supplier_Name` VARCHAR(100) NULL,
  `item_id` INT NULL,
  `item_dec` VARCHAR(200) NULL,
  `latest_price` DOUBLE NULL,
  `most_recent_price` DOUBLE NULL,
  `email_trigger` VARCHAR(45) NULL,
  `report_query` VARCHAR(100) NULL,
  `inventory_min` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_Receiving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_Receiving` (
  `Item_Id` INT NOT NULL,
  `Item_Name` VARCHAR(200) NULL,
  `Item_Desc` VARCHAR(200) NULL,
  `po_Number` VARCHAR(100) NULL,
  `Invoice_Number` VARCHAR(50) NULL,
  `Bill_Of_ladding` VARCHAR(200) NULL,
  `Quantity_Received` INT NULL,
  `Cost_Per_Item` DOUBLE NULL,
  `Total_Cost` DOUBLE NULL,
  `Tax` DOUBLE NULL,
  PRIMARY KEY (`Item_Id`),
  CONSTRAINT `fk_Inventory_Receiving_Inventory_Reordering_Alerts1`
    FOREIGN KEY (`Item_Id`)
    REFERENCES `mydb`.`Inventory_Reordering_Alerts` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Items` (
  `Item` VARCHAR(200) NULL,
  `Desc` VARCHAR(200) NULL,
  `Price` DOUBLE NULL,
  `unit_of_measure` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cycle_Counts_Override_Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cycle_Counts_Override_Inventory` (
  `Item` VARCHAR(200) NULL,
  `Item_Desc` VARCHAR(200) NULL,
  `Quantity_On_Hand` INT NULL,
  `New_Quantity` INT NULL,
  `Difference` INT NULL,
  INDEX `fk_Cycle_Counts_Override_Inventory_Items1_idx` (`Item` ASC),
  CONSTRAINT `fk_Cycle_Counts_Override_Inventory_Items1`
    FOREIGN KEY (`Item`)
    REFERENCES `mydb`.`Items` (`Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
